# Generated by Django 4.2.1 on 2023-06-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_FirstName', models.CharField(max_length=30)),
                ('person_LastName', models.CharField(max_length=30)),
            ],
        ),
    ]
